FROM python:3.11-slim AS build

# RUN apt-get update
RUN apt-get update && apt-get install -y gcc python3-dev
RUN apt-get install net-tools
RUN pip install --upgrade pip

COPY . /app
# COPY ./script/findport.sh /app/findport.sh

WORKDIR /app

RUN pip install -e .

WORKDIR /app



